### ISSUE TITLE
Circular symbol for colors

### ISSUE THREAD

**Issue by jeevithakannan2** [LivacoNew/CrabFetch#45]
**What would you like to see added to CrabFetch?**
Fastfetch like colors in circular symbol.

I searched through the docs and couldn't find anything related to this in crabfetch.

Fastfetch allows user to configure how the colors will be displayed
For example by setting

```
"symbol": "circle"
```

**Comment by jeevithakannan2** [comment]
You can achieve this using the following 

```toml
color_margin = 1
color_character = ""
color_use_background = false
```
Adding above will output like this

![Image](https://github.com/user-attachments/assets/25028bb5-3989-4401-ab8e-23487b582ac6)

Still I wonder why color is used in general config and not a separate module ??
